[package]
name = "botnet_replay_viewer"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
botnet = { version = "0.1", path = "../botnet" }
botnet_api = { version = "0.1", default-features = false, path = "../botnet_api" }
macroquad = "0.3"
rkyv = "0.7"
