# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/botnet/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/botnet_api/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/botnet_api_derive/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/botnet_replay_viewer/" # Location of package manifests
    schedule:
      interval: "weekly"
