[package]
name = "example_bot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
botnet_api = { version = "0.1", path = "../botnet_api" }
serde = { version = "1.0", features = ["derive"] }
